import { IPrize, TYPE_PRIZE, TYPE_RECEIVE } from "../../../Utils/Types";

export const EVENT_DASH_RUSH = {
    SHOW_UI_AGAIN: "EVENT_DASH_RUSH_SHOW_UI_AGAIN",
    UPDATE_BOT_RACE: "EVENT_DASH_RUSH_UPDATE_BOT_RACE",
    NOTIFICATION_ITEMS: "EVENT_DASH_RUSH_NOTIFICATION_ITEMS",
    NOTIFICATION_FORCE_CLOSE: "EVENT_DASH_RUSH_NOTIFICATION_FORCE_CLOSE",
    NOTIFICATION_TEXT: "EVENT_DASH_RUSH_NOTIFICATION_TEXT",
    FORCE_END: "EVENT_DASH_RUSH_FORCE_END",
    FORCE_WAIT_TO_JOIN: "EVENT_DASH_RUSH_FORCE_WAIT_TO_JOIN"
}

export const CONFIG_DR = {
    TIME_DELAY: 60 * 30,
    DR_MAX_PLAYER_JOIN: 5,
    DR_MAX_TIME_EVENT: 60 * 60 * 2,         // 60 *60 *2     // test 60 * 5
    DR_MAX_PROGRESS: 7,                     // 7             // test 3
    DR_TIME_AUTO_INCREASE_SCORE: 60 * 6,    // 60 * 6        // test 60
    DR_DATA_PRIZE: [
        new IPrize(TYPE_PRIZE.MONEY, TYPE_RECEIVE.NUMBER, 1000),
        new IPrize(TYPE_PRIZE.SORT, TYPE_RECEIVE.NUMBER, 1),
        new IPrize(TYPE_PRIZE.SHUFFLE, TYPE_RECEIVE.NUMBER, 1)
    ]
}

export enum STATE_DR {
    WAIT_TO_JOIN,
    JOINING,
    WAIT_TO_RECEIVE_PRIZE,
    DELAY_WIN,
    DELAY_LOSE
}