import { _decorator, Component, Node } from 'cc';
const { ccclass, property } = _decorator;

export enum STATE_INFO_PACK_ET {
    UNLOCK,
    LOCK,
    BUY_DONE
}

export enum STATE_ET {
    JOINING,
    DELAY_JOIN_AGAIN,
}

export const EVENT_ENDLESS_TREASURE = {
    NOTIFICATION: "EVENT_ENDLESS_TREASURE_NOTIFICATION",
    BUY_PACK_SUCCESS: "EVENT_ENDLESS_TREASURE_BUY_PACK_SUCCESS",
    GET_IMAGE_COIN: "EVENT_ENDLESS_TREASURE_GET_IMAGE_COIN",
    UPDATE_UI_INCREASE_ENDLESS_TREASURE: "EVENT_ENDLESS_TREASURE_UPDATE_UI_INCREASE_ENDLESS_TREASURE"
}

export const CONFIG_ET = {
    TIME_LONG_ENDLESS_TREASURE: 60 * 60 * 24 * 7,   // 60 * 60 * 24 * 7
    TIME_DELAY_ENDLESS_TREASURE: 60 * 60 * 24 * 3   // 60 * 60 * 24 * 3
}